export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0a0e14",
        "outline-variant": "#3a494a",
        background: "#10141a",
        "error-container": "#93000a",
        outline: "#849495",
        "on-primary-fixed": "#002021",
        "primary-fixed": "#63f7ff",
        "on-error-container": "#ffdad6",
        "on-primary": "#003739",
        "tertiary-container": "#e5d7ff",
        "on-secondary-container": "#520049",
        "on-tertiary-fixed": "#23005b",
        error: "#ffb4ab",
        "surface-container-low": "#181c22",
        "on-surface-variant": "#b9caca",
        "on-background": "#dfe2eb",
        "on-tertiary-container": "#751fff",
        "inverse-surface": "#dfe2eb",
        surface: "#10141a",
        "surface-container": "#1c2026",
        "inverse-primary": "#00696e",
        "on-tertiary-fixed-variant": "#5700c9",
        primary: "#e9feff",
        "primary-fixed-dim": "#00dce5",
        "surface-container-highest": "#31353c",
        "surface-dim": "#10141a",
        "on-primary-fixed-variant": "#004f53",
        "on-surface": "#dfe2eb",
        "on-tertiary": "#3c0090",
        "on-secondary-fixed": "#3a0033",
        "surface-variant": "#31353c",
        "surface-bright": "#353940",
        "on-primary-container": "#006c71",
        "primary-container": "#00f5ff",
        "secondary-fixed-dim": "#fface8",
        "tertiary-fixed-dim": "#d1bcff",
        tertiary: "#fef8ff",
        "on-secondary-fixed-variant": "#840076",
        secondary: "#fface8",
        "surface-tint": "#00dce5",
        "tertiary-fixed": "#e9ddff",
        "on-secondary": "#5e0053",
        "secondary-fixed": "#ffd7f0",
        "secondary-container": "#ff24e4",
        "inverse-on-surface": "#2d3137",
        "surface-container-high": "#262a31",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
